### ISSUE TITLE
Would it be possible to get this working on a 3.5.0 kernel?

### ISSUE THREAD

**Issue by joeytwiddle** [hanipouspilot/focaltech-dkms#2]
I am having issues with fans on this Asus X453M, with 3.19 and 4.2 kernels, but the 3.5.0 kernels work fine ... apart from the touchpad!

Is it possible to get this dkms business working on a 3.5.0 kernel, or is it something only added since then?

How about on Ubuntu 12.04?

**Comment by hanipouspilot** [comment]
No. It is not possible to do it on kernels < 3.17.

**Comment by joeytwiddle** [comment]
Understood, cheers. :)
