### ISSUE TITLE
4.x kernel support

### ISSUE THREAD

**Issue by pvdz** [hanipouspilot/focaltech-dkms#4]
Any chance you could port this to support 4.x kernels? The latest is fine for me (most, probably). 

Also thanks for putting this up in the first place.

// open bugs on this I'm currently "tracking";

https://bugzilla.kernel.org/show_bug.cgi?id=120181
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1620811
http://www.spinics.net/lists/linux-input/msg46766.html

// source that led me here

https://wiki.archlinux.org/index.php/Touchpad_Synaptics#ASUS_Touchpads_only_recognised_as_PS.2F2_FocalTech_emulated_mouse

**Comment by hanipouspilot** [comment]
Focaltech touchpads are supported by Linux kernels since 4.1. The code has been commited upstream.

**Comment by pvdz** [comment]
If by support you mean "recognized as a mouse", then sure and I'm sorry for wasting your time.

As it stands "our" particular model is only recognized as a regular mouse. We can click and double click but there's no standard touch support. See the linked bug threads for similar reports.

**Comment by hanipouspilot** [comment]
What is "your" particular model? Why do you think it is a Focaltech? All code that is used here works in mainline kernels. If you have some other touchpad, then how is it related?

Does "your particular model" work with this code?

**Comment by hanipouspilot** [comment]
The bug links you gave show that the issue is with some new i2c touchpad.
It is not supported yet. Why people cal it Focaltech, I have no idea.

2016-09-22 11:44 GMT+03:00 Peter van der Zee notifications@github.com:

**Comment by pvdz** [comment]
Hm, actually... you may be on to something here. I was going by the many replies (since linux inspection did not show that). But now you mention it I stumble on [this pdf](http://www.uefi.org/sites/default/files/resources/PNPID_List.pdf) which lists the PNPid's for companies. "FocalTech Systems Co., Ltd." is `FTS` while `FTE` is for "Frontline Test Equipment Inc."

Thanks for the insight!

**Comment by hanipouspilot** [comment]
Anyway the code here and in the kernel is for PS/2 Focaltech touchpads with PNP ids FLT0101-FLT0103.
Your touchpad is not related at all. You can stop searching since there is no support for it anywhere till someone writes a driver.
